# fly.toml app configuration file generated for wordish-backend on 2024-01-10T22:03:39-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wordish-backend"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
