import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <div className="rootHeader">
          <Link href="/">Wordle</Link>
          <Link href="/example">Example</Link>
        </div>
        <div className={inter.className}>{children}</div>
      </body>
      
    </html>
  )
}
